#[derive(Clone, Copy, Debug)]
pub enum AddressingMode {
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Accumulator,
    Immediate,
    Implied,
    IndexedIndirect,
    Indirect,
    IndirectIndexed,
    Relative,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
}

#[derive(Clone, Copy, Debug)]
pub struct InstructionInfo {
    pub size: u8,
    pub cycles: u8,
    pub page: u8,
    pub mode: AddressingMode,
}

pub const INFO: [InstructionInfo; 256] = [
    InstructionInfo {
        size: 1,
        cycles: 7,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 3,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Accumulator,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Accumulator,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 1,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 3,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Accumulator,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 3,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 1,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Accumulator,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 5,
        page: 0,
        mode: AddressingMode::Indirect,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageY,
    },
    InstructionInfo {
        size: 0,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 5,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 5,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageY,
    },
    InstructionInfo {
        size: 0,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 0,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndexedIndirect,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 3,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 0,
        cycles: 5,
        page: 0,
        mode: AddressingMode::ZeroPage,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Immediate,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 3,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::Absolute,
    },
    InstructionInfo {
        size: 2,
        cycles: 2,
        page: 1,
        mode: AddressingMode::Relative,
    },
    InstructionInfo {
        size: 2,
        cycles: 5,
        page: 1,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 0,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 8,
        page: 0,
        mode: AddressingMode::IndirectIndexed,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 4,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 2,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 0,
        cycles: 6,
        page: 0,
        mode: AddressingMode::ZeroPageX,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 1,
        cycles: 2,
        page: 0,
        mode: AddressingMode::Implied,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteY,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 4,
        page: 1,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 3,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
    InstructionInfo {
        size: 0,
        cycles: 7,
        page: 0,
        mode: AddressingMode::AbsoluteX,
    },
];

pub const NAMES: [&str; 256] = [
    "BRK",
    "ORA (@,X)",
    ".byte $02",
    ".byte $03",
    ".byte $04",
    "ORA @",
    "ASL @",
    ".byte $07",
    "PHP",
    "ORA #@",
    "ASL",
    ".byte $0b",
    ".byte $0c",
    "ORA @",
    "ASL @",
    ".byte $0f",
    "BPL @",
    "ORA (@),Y",
    ".byte $12",
    ".byte $13",
    ".byte $14",
    "ORA @,X",
    "ASL @,X",
    ".byte $17",
    "CLC",
    "ORA @,Y",
    ".byte $1a",
    ".byte $1b",
    ".byte $1c",
    "ORA @,X",
    "ASL @,X",
    ".byte $1f",
    "JSR @",
    "AND (@,X)",
    ".byte $22",
    ".byte $23",
    "BIT @",
    "AND @",
    "ROL @",
    ".byte $27",
    "PLP",
    "AND #@",
    "ROL",
    ".byte $2b",
    "BIT @",
    "AND @",
    "ROL @",
    ".byte $2f",
    "BMI @",
    "AND (@),Y",
    ".byte $32",
    ".byte $33",
    ".byte $34",
    "AND @,X",
    "ROL @,X",
    ".byte $37",
    "SEC",
    "AND @,Y",
    ".byte $3a",
    ".byte $3b",
    ".byte $3c",
    "AND @,X",
    "ROL @,X",
    ".byte $3f",
    "RTI",
    "EOR (@,X)",
    ".byte $42",
    ".byte $43",
    ".byte $44",
    "EOR @",
    "LSR @",
    ".byte $47",
    "PHA",
    "EOR #@",
    "LSR",
    ".byte $4b",
    "JMP @",
    "EOR @",
    "LSR @",
    ".byte $4f",
    "BVC @",
    "EOR (@),Y",
    ".byte $52",
    ".byte $53",
    ".byte $54",
    "EOR @,X",
    "LSR @,X",
    ".byte $57",
    "CLI",
    "EOR @,Y",
    ".byte $5a",
    ".byte $5b",
    ".byte $5c",
    "EOR @,X",
    "LSR @,X",
    ".byte $5f",
    "RTS",
    "ADC (@,X)",
    ".byte $62",
    ".byte $63",
    ".byte $64",
    "ADC @",
    "ROR @",
    ".byte $67",
    "PLA",
    "ADC #@",
    "ROR",
    ".byte $6b",
    "JMP (@)",
    "ADC @",
    "ROR @",
    ".byte $6f",
    "BVS",
    "ADC (@),Y",
    ".byte $72",
    ".byte $73",
    ".byte $74",
    "ADC @,X",
    "ROR @,X",
    ".byte $77",
    "SEI",
    "ADC @,Y",
    ".byte $7a",
    ".byte $7b",
    ".byte $7c",
    "ADC @,X",
    "ROR @,X",
    ".byte $7f",
    ".byte $80",
    "STA (@,X)",
    ".byte $82",
    ".byte $83",
    "STY @",
    "STA @",
    "STX @",
    ".byte $87",
    "DEY",
    ".byte $89",
    "TXA",
    ".byte $8b",
    "STY @",
    "STA @",
    "STX @",
    ".byte $8f",
    "BCC @",
    "STA (@),Y",
    ".byte $92",
    ".byte $93",
    "STY @,X",
    "STA @,X",
    "STX @,Y",
    ".byte $97",
    "TYA",
    "STA @,Y",
    "TXS",
    ".byte $9b",
    ".byte $9c",
    "STA @,X",
    ".byte $9e",
    ".byte $9f",
    "LDY #@",
    "LDA (@,X)",
    "LDX #@",
    ".byte $a3",
    "LDY @",
    "LDA @",
    "LDX @",
    ".byte $a7",
    "TAY",
    "LDA #@",
    "TAX",
    ".byte $ab",
    "LDY @",
    "LDA @",
    "LDX @",
    ".byte $af",
    "BCS @",
    "LDA (@),Y",
    ".byte $b2",
    ".byte $b3",
    "LDY @,X",
    "LDA @,X",
    "LDX @,Y",
    ".byte $b7",
    "CLV",
    "LDA @,Y",
    "TSX",
    ".byte $bb",
    "LDY @,X",
    "LDA @,X",
    "LDX @,Y",
    ".byte $bf",
    "CPY #@",
    "CMP (@,X)",
    ".byte $c2",
    ".byte $c3",
    "CPY @",
    "CMP @",
    "DEC @",
    ".byte $c7",
    "INY",
    "CMP #@",
    "DEX",
    ".byte $cb",
    "CPY @",
    "CMP @",
    "DEC @",
    ".byte $cf",
    "BNE @",
    "CMP (@),Y",
    ".byte $d2",
    ".byte $d3",
    ".byte $d4",
    "CMP @,X",
    "DEC @,X",
    ".byte $d7",
    "CLD",
    "CMP @,Y",
    ".byte $da",
    ".byte $db",
    ".byte $dc",
    "CMP @,X",
    "DEC @,X",
    ".byte $df",
    "CPX #@",
    "SBC (@,X)",
    ".byte $e2",
    ".byte $e3",
    "CPX @",
    "SBC @",
    "INC @",
    ".byte $e7",
    "INX",
    "SBC #@",
    "NOP",
    ".byte $eb",
    "CPX @",
    "SBC @",
    "INC @",
    ".byte $ef",
    "BEQ @",
    "SBC (@),Y",
    ".byte $f2",
    ".byte $f3",
    ".byte $f4",
    "SBC @,X",
    "INC @,X",
    ".byte $f7",
    "SED",
    "SBC @,Y",
    ".byte $fa",
    ".byte $fb",
    ".byte $fc",
    "SBC @,X",
    "INC @,X",
    ".byte $ff",
];
